# Generated by Django 4.0.5 on 2022-06-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Published', 'Published'), ('REVIEW', 'Review'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('altered_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Published', 'Published'), ('REVIEW', 'Review'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('altered_on', models.DateField(auto_now_add=True)),
                ('changedon', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
